name: shop_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc: ^8.1.1
  flutter_bloc: ^8.1.2
  flutter_conditional_rendering: ^2.0.0
  dio: ^5.2.1+1
  shared_preferences: ^2.2.0

flutter:
  uses-material-design: true
